### ISSUE TITLE
Dahu does not create new project

### ISSUE THREAD

**Issue by chenshuiluke** [dahuapp/dahu#117]
I downloaded Dahu 0.3, updated my Java to version 8, opened a terminal and did the following:

sudo java -jar Dahu-0.3.jar

The Dahu window opens properly, but nothing happens once I specify a folder to create a new project. I also tried doing:
sudo java -jar Dahu-0.3.jar blahblah

It seems to fool Dahu into thinking blahblah is a proper project. Then, I clicked the new project button again and it seems to work :/

**Comment by Jean-Bapt** [comment]
Hello,

Thank you for your issue. I expect the next release to be processed in june 2015. I'll try to have a look on it at the beginning of year 2015... Maybe other contributors could fix it before ? :)
