### ISSUE TITLE
Drag and drop does not work on Linux System

### ISSUE THREAD

**Issue by Jean-Bapt** [dahuapp/dahu#14]
Hello,

There is a problem like the one we had with the DirectoryChooser with javafx.
The drag and drop (to edit mouse position) perfectly works on Windows System but exceptions are risen on Linux System.

I think that the problem is due to the javafx implentation on Linux but I'm not sure. Does it work on Mac OS ? How can we solve this problem ?

**Comment by barraq** [comment]
it works on mac. however I see some strange "file" icon whenever I drag the mouse.

**Comment by Jean-Bapt** [comment]
Thanks for this response. So linux seems to have a problem with java fx (or javascript... ?).

**Comment by barraq** [comment]
This is a JavaFX bug for the linux platform.

**Comment by moy** [comment]
Rémi Barraquand notifications@github.com writes:

> This is a JavaFX bug for the linux platform.

I also have the bug on Linux (Debian, x86_64, java version "1.7.0_21").

Has it been reported somewhere? If so, it would be nice to point to the
Java bug here. If not, it would be nice to report it.

## 

Matthieu Moy
http://www-verimag.imag.fr/~moy/

**Comment by Jean-Bapt** [comment]
The research I done to find if similar bug has been reported was unsuccessful. I am going to create a Jira issue on https://javafx-jira.kenai.com

**Comment by Jean-Bapt** [comment]
You can the issue by following this link : https://javafx-jira.kenai.com/browse/RT-31158

**Comment by Jean-Bapt** [comment]
the issue was fixed today : https://javafx-jira.kenai.com/browse/RT/fixforversion/10380

I've just received this e-mail : 

Peter Z. a mis à jour RT-31158:
`Etat: Résolue  (a été: New)
    Version(s) corrigée(s): Lombard
    Résolution: Corrigé`

Now, we have to update from Presidio to Lombard release for javafx
