### ISSUE TITLE
uploading binary on gitHub

### ISSUE THREAD

**Issue by Jean-Bapt** [dahuapp/dahu#18]
Hello,

Even if some bugs still exist in the current version, what do you think about uploading binary version for Windows, Mac and Linux on gitHub, for other users who don't want to compile the project (my homemates for instance) ?

**Comment by moy** [comment]
Sure, please do. If you upload binaries, it would make sense to start numbering and tagging versions. Can you tag a 0.1 version number, or something like this?

**Comment by Jean-Bapt** [comment]
And where can we stock the binaries ? We just create directories like 'binary->windows|mac|linux' ? Or it is better to create a new Git repository (or a new branch) where the user can just find sources and some manual ?
Maybe the best is a new repository with branch for each tag... isn't it ?

**Comment by moy** [comment]
Please, don't commit binaries in the Git repo itself. Not sure what's the best way to offer binaries download, but a quick google finds this: http://stackoverflow.com/questions/10346370/what-is-the-best-practice-of-distributing-binaries-from-a-github-project

I think it's time to create gh-pages for Dahu, where we can have the binaries download, and a gallery of tutorials generated with Dahu. Binaries will be rather small and seldomly downloaded, so the recommendation of Amazon S3 seems a bit overkill.

**Comment by barraq** [comment]
I agree with @moy. The best things to do will be:
- start tagging each version
- create a new release as follow https://github.com/blog/1547-release-your-software
- create a dahuapp-web repository
- put the source code for the web page in the master branch
- create a gh-pages branch and have the browsable version on it
- create a download/bin directory in this gh-pages with the bin in it
- link those bins in the download.html page ;)

**Comment by moy** [comment]
Just uploaded a .jar. I'm closing the issue, but feel free to add other binary forms (e.g. .exe or Java Web Start).
