### ISSUE TITLE
Allow linking to individual slides with anchors

### ISSUE THREAD

**Issue by moy** [dahuapp/dahu#21]
Currently, an external link can point to presentation.html, which shows the first slide by default. It would be nice to be able to link to presentation.html#some-anchor to jump directly to a particular slide. This would require adding a unique identifier to each slides to have stable anchor names.

**Comment by moy** [comment]
It's almost there, but not quite: we can link to an anchor from an external page, but changing the anchor does not work (it does not reload the page, hence does not re-execute the initialization code).

I was expecting to be able to use <a href="#some-anchor">...</a> within tooltips to navigate from one action to another, but it does not seem to work. We need to react to anchor change event. This should work:

http://stackoverflow.com/questions/2161906/handle-url-anchor-change-event-in-js

**Comment by beckerdenis** [comment]
Fixed in commit f0771f0ac54d55c033e175e2020013bb189b8839.

**Comment by moy** [comment]
Cool :-). Thanks!
