### ISSUE TITLE
[Dahu-03] Package JavaScript dependencies with generated presentations

### ISSUE THREAD

**Issue by moy** [dahuapp/dahu#30]
We currently generate

<script src="http://code.jquery.com/jquery-1.9.1.min.js">
</script>

It's OK when publishing to a public website, but it would be better to include (at least optionally) JQuery (and possibly future other dependencies) in the generated presentations, so that they can be viewed offline, or behind a firewall blocking code.jquery.com.

**Comment by barraq** [comment]
This feature is now supported in Dahu-Next.
