### ISSUE TITLE
A nice logo for the webpage?

### ISSUE THREAD

**Issue by moy** [dahuapp/dahu#34]
Anyone with good drawing skills to design us a nice logo?

**Comment by barraq** [comment]
I am working with some designers from the ARIES school, maybe they can help!
The only thing is that I need to tell them what we expect, e.g. do we want a dahu in the logo?

**Comment by moy** [comment]
A Dahu on the logo would be fun :-). That would be nice to have
a reference to the web too. Maybe a Dahu with a mouse pointer?

## 

Matthieu Moy
http://www-verimag.imag.fr/~moy/

**Comment by barraq** [comment]
propositionA-v0.1 ![dahu](https://f.cloud.github.com/assets/293498/1291477/1e93ee7a-3043-11e3-8323-126603059a07.png)
