### ISSUE TITLE
Running Dahu from JAR file doesn't work

### ISSUE THREAD

**Issue by moy** [dahuapp/dahu#40]
The editor is launched, but images are not displayed. The binary JAR I had uploaded is actually broken, I'm removing it from the release.

**Comment by moy** [comment]
OK, we're in trouble ...

It seems we're hit by this issue

http://stackoverflow.com/questions/17993971/javafx-2-2-generated-image-not-shown-after-building-jar-file
http://stackoverflow.com/questions/12288697/can-not-display-local-image-file-as-webengine-image-src-attribute

We can either:
- Use data: URI to load the images (I don't like it at all)
- Use WebEngine.loadContent() instead of load(url). I didn't test, but I suspect local URLs would be accessible then. JavaScript will likely be an issue.
- Manage to get dahuapp.html and .js files as files (either package Dahu with them outside the jar file, or extract them on-the-fly to a temporary directory)

None seem really satisfactory ...

Any better idea?

**Comment by moy** [comment]
I tried the second option, and as I suspected, it loads the HTML, but fails to load the CSS and JavaScript. We'd need to inject individual CSS and js files in the webview. Even more painful than the data: URI.

FWIW, the patch looked like this:

```
--- a/editor/src/main/java/io/dahuapp/editor/app/DahuApp.java
+++ b/editor/src/main/java/io/dahuapp/editor/app/DahuApp.java
@@ -2,6 +2,7 @@ package io.dahuapp.editor.app;

 import io.dahuapp.editor.proxy.DahuAppProxy;
 import io.dahuapp.editor.utils.Dialogs;
+import java.io.BufferedReader;
 import javafx.application.Application;
 import static javafx.application.Application.launch;
 import javafx.application.Platform;
@@ -21,6 +22,17 @@ import javafx.stage.WindowEvent;
 import javafx.util.Callback;
 import java.util.List;
 import java.io.File;
+import java.io.FileNotFoundException;
+import java.io.IOException;
+import java.io.InputStream;
+import java.io.InputStreamReader;
+import java.net.URL;
+import java.nio.file.Files;
+import java.nio.file.Path;
+import java.nio.file.Paths;
+import java.util.Scanner;
+import java.util.logging.Level;
+import java.util.logging.Logger;

 /**
  * Main class of the application. Runs the GUI to allow the user to take
@@ -108,9 +120,25 @@ public class DahuApp extends Application {
     private void initDahuApp(final Stage primaryStage) {
         webview = new WebView();
         webview.setContextMenuEnabled(false);
+        final URL location = getClass().getResource("dahuapp.html");
+        String content = null;
+        try {
+            InputStream in = location.openStream();
+            InputStreamReader is = new InputStreamReader(in);
+            StringBuilder sb = new StringBuilder();
+            BufferedReader br = new BufferedReader(is);
+            String read = br.readLine();
+            while (read != null) {
+                sb.append(read);
+                read = br.readLine();
+            }
+            content = sb.toString();
+        } catch (IOException e) {
+            System.err.println(e);
+        }
         // load main app
-        webview.getEngine().load(getClass().getResource("dahuapp.html").toExternalForm());
+        webview.getEngine().loadContent(content);

         // extend the webview js context
         webview.getEngine().getLoadWorker().stateProperty().addListener(new ChangeListener<Worker.State>() {
```

**Comment by barraq** [comment]
Could you detail a little bit more the steps you follow so that I can reproduce the error: I don't have it :o

_p.s._ normally in order to deploy the app we should run _gradle build_ which execute the jfxdeploy task that creates some "bundle" folder within the > build/distribution directory. The application should then not be started from the jar but through the generated bundle. It seems however that the bundle generation process is broken :/ I'll dig into it

**Comment by moy** [comment]
Yes, there's another problem with the generated bundle. I didn't investigate much, but worked around with "gradle uberjar" (see commit ba54376c1b3).

Steps to reproduce this issue (images not loaded):

gradle uberjar
java -jar build/libs/Dahu-0.2-SNAPSHOT.jar

**Comment by barraq** [comment]
Ok, I just fixed the bundle generation (on linux 64 bits there is still a small bug, check #41 for a small fix) do you still encounter the same issue when now running from the generated bundle?

I'll have a look at uberjar.

**Comment by moy** [comment]
Reported to JavaFX's JIRA: https://javafx-jira.kenai.com/browse/RT-33570

**Comment by moy** [comment]
The bundle now accepts to start (thanks!), but since the bundle uses a .jar internally, I still get the bug with images not displaying.

**Comment by barraq** [comment]
Indeed I got the bug too finally :/

Regarding this issue... I really think that it is not going to get fixed anytime soon... this involve security issues and therefore they are going to be really slow to address the issue.

On the other hand, one quick solution would be to extract our resources at runtime and then load those extracted resources using file:// rather than loading from the jar file as jar:// ! This would solve lot of issues at once :)

What do you think?

**Comment by moy** [comment]
OK, it's not the cleanest code I ever wrote, but 760f5a6911 works around the issue.

I could launch the editor, load a project and generate a presentation both from the uberjar and from the bundle. Testers and reviewers appreciated (close the issue if it's OK).
