### ISSUE TITLE
A way to generate a presentation without launching the GUI

### ISSUE THREAD

**Issue by moy** [dahuapp/dahu#42]
I'd like to be able to re-generate multiple presentations, e.g. from a Makefile, at once. Currently, I need a few clicks per presentation, it should be possible to do that with e.g.

`dahu --generate-presentation my-project`

and ideally be able to specify the output directory with eg.

`dahu --generate-presentation my-project -o presentation`

**Comment by barraq** [comment]
In addition it would be cool to create a new presentation from a bunch of images like

```
> dahu --generate-presentation project --from /some/path/
```

This will get all the pics from the given directory. Ordering can be using the name of the pics or the date of creation of the pics: that being an option that can be changed by the user.

**Comment by barraq** [comment]
@moy now you can generate a screencast using the CLI !

To use it you have to build the CLI:

```
$ /gradlew :dahu:cli:installApp
```

The binary is available in _dahu/cli/build/install/DahuCLI/bin_.
Then run the following

```
$ DahuCLI generate path/to/presentation.dahu
```

Enjoy ;)
