### ISSUE TITLE
Hide main window content when hitting capture key

### ISSUE THREAD

**Issue by barraq** [dahuapp/dahu#44]
When hitting the capture key in capture mode it would be cool to hide the main window content to avoid "screenshot loop" like shown here

![66b60288-63b0-4bef-8bb1-f1cf9eb5b167](https://f.cloud.github.com/assets/293498/1341243/7c0d1592-3645-11e3-8cfb-2a2dba590b98.png)

this would allow to do better screencasting -- like do a screencast of dahu with dahu !

**Comment by moy** [comment]
Actually, you can already do a screencast of Dahu in Dahu: just use two instances (one for the demo, and the other doing the actual capture).

Hiding the content of the main window does not seem such a good solution to me: the capture would contain a blank pane in a place where you may want to have actual content. That would be very surprising for the user to capture something and see something else in the image.

**Comment by barraq** [comment]
Indeed having 2 instances of dahu is good enough :)
