### ISSUE TITLE
Make the menubar go native

### ISSUE THREAD

**Issue by barraq** [dahuapp/dahu#46]
The menu bar is currently implemented in HTML/CSS/JS.
To better integrate with native platforms it would be better to **make it native by using the dedicated javafx classes**.

In UI systems like MacOS or Gnome the menu bar will be detached from the application like native apps. For other systems like Windows the new Look&Feel of JavaFx8 will better match the native UI (see http://fxexperience.com/2013/01/modena-new-theme-for-javafx-8/)

**Comment by benabbon** [comment]
We can close this issue now as it is well handled in dahu next.
