### ISSUE TITLE
Open upgraded dahu files breaks

### ISSUE THREAD

**Issue by benabbon** [dahuapp/dahu#54]
Upgraded files don't work when we try to open them, but old dahu files are loaded successfuly.

**Comment by barraq** [comment]
Is this the same issue as describe here #53 ?
Could you provide more details ?

**Comment by benabbon** [comment]
No it's different.
Here it's the new format of dahu files that cannot be read from a file.
For instance, we open presentation.dahu, which an old dahu file. The editor opens the file successfuly and creates presentation.dahu.old with the old file, and presentation.dahu with the new one. When we try to reopen that new one : presentation.dahu, it crashes.

**Comment by benabbon** [comment]
The error looks like this : TypeError: 'undefined' is not a function (evaluating 'obj[implementation](name, callback, this)') with a backtrace from java.

**Comment by barraq** [comment]
You should start catching exception to better handle error. 
For instance a simple example that just log the error. This will get you to the bug.

```
    try {
        // Code throwing an exception

        var layout = new DahuLayout();
        layout.render();
        app.frame.show(layout);

        // show screens in filmstrip region
        layout.filmstrip.show(new FilmstripScreensView({collection: projectScreencast.get('screens')}));
    } catch(e) {
        console.log(e.stack);
    }
```

**Comment by barraq** [comment]
I spotted the bug, I'll explain it to you and post a patch (this is kind of tricky)
