### ISSUE TITLE
dahu editor for smartphones and tablets

### ISSUE THREAD

**Issue by Jean-Bapt** [dahuapp/dahu#57]
It could be great that the Dahu can be use to make tutorials for smartphones or tablets sofwares.
The dahu editor can be compiled to run on these devices (or the conceptor use a emulator / virtualization machine to make the tutos).
Smartphones and tablets have no mouse cursor. But we can imagine that we can display the fingerprint by a wave (like a stone in water). The finger swipe could be displayed by a dynamic line. Actions with two fingers (like zoom) can also be shown with two arrows...

**Comment by barraq** [comment]
It would be a lot easier to use Dahu on Desktop and take screenshot of the mobile-emulator's screen (iOS, Android, Windows).
