### ISSUE TITLE
Start using MV* Javascript framework

### ISSUE THREAD

**Issue by barraq** [dahuapp/dahu#9]
In the next iteration we should start using a MV\* JavaScript framework for the editor in order to better structure the app. AMong the choice we have for instance http://backbonejs.org/ or http://emberjs.com/. While EmberJS is maybe a little bit to heavy for our project (but more powerful)  BackboneJS seems to me a good choice.
By using BackboneJS we will be able to bind event from model to view and view to model easily, but also improve a lot the scalability of the app.

**Comment by benabbon** [comment]
I think this can be closed now as it is handled in Dahu next. Or should we keep it until we have a stable & final version of the latter ?

**Comment by barraq** [comment]
Indeed, i'm closing the issue.
