### ISSUE TITLE
Pure HTML vs SVG vs Canvas editor

### ISSUE THREAD

**Issue by barraq** [dahuapp/dahu#96]
In the process of refactoring Dahu (see branch [next](https://github.com/dahuapp/dahu/tree/next)) we started to rethink/redesign the way "screens" from a screencast are both edited and rendered.

![dahu-screen](https://cloud.githubusercontent.com/assets/293498/3343306/46f3ee0a-f89e-11e3-81aa-2e0a32c33f1a.png)

In the current version of Dahu, objects (e.g. cursor, tooltips, etc.) from a screen are rendered using pure HTML elements. Web based PowerPoint like editor on the market are using SVG or Canvas instead of HTML to render the 'editing' part. For instance Google Presentation is using SVG to edit slides.

In Dahu Next we would like to have the same rendering for both the Editor and the Player. The question is, should this rendering be HTML based, SVG basedo or Canvas based ?

I would like therefore to open the discussion to see the pros and cons of both HTML, SVG, Canvas approaches to edit and render 'screens' of a Dahu screencast.

Here is the information I was able to gather. I'll update the pros and cons as the discussion goes on.
# SVG approach

SVG is 99% adapted to our problems.

_Libraries:_
- http://snapsvg.io/ by adobe
- http://www.svgjs.com/
- ...

_Pros:_ 
- support scaling without doing anything...
- support many kind of objects like circles, rectangles, path, etc...
- support import of external SVG objects
- animating SVG in Deck.js is already supported
- scale, move, rotate is already supported by SVG library such as http://fabricjs.com
- basic support is provided for IE>8, Safari>6

_Cons:_ 
- little bit more complicated to display tooltips with HTML code inside SVG... There exists a [foreignObject](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject) element that does the job but which is not supported yet in IE. Therefore if we want to have HTML formatted text in tooltips we will have to do as in Google Presentation: split each word, wrap each word in a text element with a dedicated style and put all these words in a group.... Otherwise we can just forget about formatted text in tooltips ;)
- advanced support is not supported by IE<11
# HTML approach

_Pros:_
- tooltip with HTML formatted text are supported without doing anything
- scaling can be done using CSS transform

_Cons:_
- requires a support for latest CSS transformation (IE>9)
# Canvas approach

_Libraries:_
- http://fabricjs.com/

_Cons:_
- it is rasterized
- complicated to render html in it

@moy, @twitwi, @remyd please share you point of view ;)

**Comment by twitwi** [comment]
(I lost my comment by clicking on one of my links in the "preview" of my github comment... so this version is less reviewed...)

I wouldn't go for canvases... it might get complicated to render html in it... and it is rasterized...

If a lot of complicated shapes, a pure SVG solution might be a solution. The best solution (depending on the targeted browsers) is probably to use HTML and use inline SVG if needed for a few shapes (see next paragraph on HTML scaling).
http://caniuse.com/#search=inline%20svg

If the "model" is mostly well represented in HTML, my choice would definitely go for the HTML version. The scaling problem is actually not a problem (depending on the targeted browsers): you can just "design/edit" using a fixed size (e.g., the dimensions of the captures images), place your screen image, your tooltips and cursor all in a container of this exact size, and use CSS transform to scale this container to the desired display size.
This is what I ended up doing in deck.js, see for example the technical demo of the fit extension. The added bonus is that you're not restricted to using percents in your design and can use "absolute" pixel values (relative to your capture, e.g., x from 0 to your capture width).
http://home.heeere.com/data/deck-js-demo-2/samples/deck-fit.html
http://caniuse.com/#search=css3%20transform

**Comment by barraq** [comment]
@twitwi we are targeting modern browsers, actually the only problematic one would be IE but IE>=9 supports CSS transformation (with few hacks for IE9) to I guess this is a valid options. I'll give a shot at the CSS scaling things to see if it works fine with drag & drop, move, resize operation. Also you are making a point with the "added bonus" of using absolute coordinate :) this is indeed one of our consideration mostly within the editor! Thanks

**Comment by moy** [comment]
Keeping compatibility with old browsers (for the viewer part) would be nice, though. A friend of mine laught at me when I sent her a link to a Dahu presentation at work (at CEA, IE9 is not a "modern browser" it's science fiction ;-) ). I managed to get the presentation to work on IE7 IIRC, as there was actually nothing complex in the viewer at that time (I changed a &lt;section&gt; into a &lt;div&gt;, and it did the job).

**Comment by barraq** [comment]
@moy regarding the compatibility with HTML5 elements (section, header, nav, etc.) for 'old' IE browsers like IE7, IE8, IE9 we can use [Modernizr](http://modernizr.com/). Actually it is already included in the generated screencast (provided by default by Deck.js). If you have VMs with such browsers installed it would be nice to test Dahu next on those :)
