### ISSUE TITLE
[dahu-03] takes 3 pictures when F7 is pressed

### ISSUE THREAD

**Issue by Jean-Bapt** [dahuapp/dahu#98]
Hello,

I tried the new version of Dahu (03) on windows 7.
When in capture mode, I took 1 picture with the F7 key and then added a tooltip. (It worked pretty well, except another bug I will submit :) ). Then I switched the capture mode off.
After that, I wanted to take other screenshots and each time I pressed the F7 key, it took 3 pictures instead of 1.

**Comment by Jean-Bapt** [comment]
After testing again, I wonder if it was not an easter egg for mathematics fans.
I clicked the first time on "capture mode" and pressed F7 => 1 picture created
Switch off the capture mode.
Then I click again on "capture mode" and pressed F7 => 3 pictures created
Switch off the capture mode.
Then I click again on "capture mode" and pressed F7 => 4 new pictures created
Switch off the capture mode.
Then I click again on "capture mode" and pressed F7 => 5 new pictures created
Switch off the capture mode.
Then I click again on "capture mode" and pressed F7 => 7 new pictures created
Switch off the capture mode.
Then I click again on "capture mode" and pressed F7 => 9 new pictures created 
... and it increases the number again and again...

**Comment by twitwi** [comment]
same problem for me with the same version but on Linux 64, jdk8u20

**Comment by Jean-Bapt** [comment]
@beckerdenis : you restart the project this year my little pink turtle ?
